<?php

namespace App\Services;

use Illuminate\Http\Client\ConnectionException;
use Illuminate\Http\Client\PendingRequest;
use Illuminate\Http\Client\Response;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;
use InvalidArgumentException;
use RuntimeException;

/**
 * Delivers the app's own verification OTPs over the Semaphore SMS API
 * (PH-only numbers, OTP-dedicated route: 2 credits per 160-char SMS).
 *
 * Mirrors the PayMongoService HTTP pattern: connect-timeout, retry on 5xx /
 * transient connection errors, and a dedicated `sms` log channel. OTP codes
 * are generated by the app (OtpService / the password broker) — never by
 * Semaphore — so the cache-hashed code and the SMS code always match.
 */
class SmsService
{
    /**
     * The `{otp}` placeholder is replaced by Semaphore with the `code` value
     * sent alongside the message.
     */
    public const OTP_MESSAGE = 'GW-System verification code: {otp}. Expires in 5 minutes. Do not share.';

    private const TIMEOUT_SECONDS = 15;

    private const MAX_ATTEMPTS = 3;

    private const RETRY_SLEEP_MICROSECONDS = 100_000;

    /**
     * Sends a verification code to a Philippine mobile number through the
     * active driver. Throws InvalidArgumentException for a malformed number
     * (validated in BOTH drivers) and RuntimeException when the semaphore
     * driver has no key or Semaphore rejects the message (the queued job
     * retries).
     */
    public function sendOtp(string $phone, string $code, string $message = self::OTP_MESSAGE): void
    {
        $normalized = $this->normalizePhone($phone);

        if ($this->driver() === 'log') {
            Log::channel('sms')->info('SMS OTP (log driver — not sent)', [
                'phone' => $normalized,
                'code' => $code,
                'message' => str_replace('{otp}', $code, $message),
            ]);

            return;
        }

        $response = $this->sendWithRetry(fn (): Response => $this->request()
            ->asForm()
            ->post(config('services.semaphore.otp_endpoint'), [
                'apikey' => $this->apiKey(),
                'number' => $normalized,
                'message' => $message,
                'code' => $code,
                'sendername' => config('services.semaphore.sender_name'),
            ]));

        $payload = $response->json();

        if ($response->failed() || static::statusWasRejected($payload)) {
            Log::channel('sms')->error('Semaphore OTP send failed', [
                'status_code' => $response->status(),
                'response' => $payload,
            ]);

            throw new RuntimeException('Semaphore OTP send failed: '.$response->body());
        }

        Log::channel('sms')->info('Semaphore OTP accepted', [
            'message_id' => $payload[0]['message_id'] ?? null,
            'status' => $payload[0]['status'] ?? null,
            'recipient' => $payload[0]['recipient'] ?? null,
        ]);
    }

    /**
     * Active delivery driver: `log` (dev/test sandbox) or `semaphore` (real).
     */
    public function driver(): string
    {
        return (string) config('services.semaphore.driver', 'log');
    }

    /**
     * True when the portal may offer the SMS channel. Always true in log mode
     * (dev/test can exercise the full flow offline); gated on the Semaphore
     * API key otherwise.
     */
    public function available(): bool
    {
        if ($this->driver() === 'log') {
            return true;
        }

        $key = config('services.semaphore.api_key');

        return is_string($key) && trim($key) !== '';
    }

    /**
     * Normalizes a Philippine mobile number to international format
     * (`639XXXXXXXXX`) for Semaphore. Accepts `09XXXXXXXXX`, `639XXXXXXXXX`
     * and `+639XXXXXXXXX` (internal spaces/dashes tolerated). Throws on any
     * other input.
     */
    public function normalizePhone(string $phone): string
    {
        $digits = preg_replace('/[^\d]/', '', $phone) ?? '';

        if ($digits === '') {
            throw new InvalidArgumentException('Phone number cannot be empty.');
        }

        if (str_starts_with($digits, '09')) {
            $digits = '63'.substr($digits, 1);
        }

        if (! str_starts_with($digits, '63') || strlen($digits) !== 12) {
            throw new InvalidArgumentException('Phone number must be a valid Philippine mobile number (09... or 639...).');
        }

        return $digits;
    }

    /**
     * The OTP endpoint answers with a JSON array of message objects. A message
     * is rejected when its status is `Failed` (case-insensitive) — anything
     * else (Queued/Pending/Sent) means Semaphore accepted it.
     */
    protected static function statusWasRejected(mixed $payload): bool
    {
        if (! is_array($payload) || ! isset($payload[0]['status'])) {
            return false;
        }

        return strtolower((string) $payload[0]['status']) === 'failed';
    }

    protected function request(): PendingRequest
    {
        return Http::timeout(self::TIMEOUT_SECONDS);
    }

    /**
     * The Semaphore API key, throwing a clear error when the configured
     * semaphore driver has none (misconfig guard — same pattern as
     * PayMongoService::secretKey()).
     */
    protected function apiKey(): string
    {
        $key = config('services.semaphore.api_key');

        if (! is_string($key) || trim($key) === '') {
            throw new RuntimeException('SEMAPHORE_API_KEY is not configured. SMS is unavailable.');
        }

        return trim($key);
    }

    /**
     * Sends a request, retrying on 5xx responses and transient connection
     * errors, exactly like PayMongoService. After the final attempt a failed
     * response is returned as-is (the caller inspects $response->failed()).
     */
    protected function sendWithRetry(callable $request): Response
    {
        for ($attempt = 1; ; $attempt++) {
            try {
                $response = $request();
            } catch (ConnectionException $e) {
                if ($attempt >= self::MAX_ATTEMPTS) {
                    throw $e;
                }

                usleep(self::RETRY_SLEEP_MICROSECONDS);

                continue;
            }

            if (! $response->serverError() || $attempt >= self::MAX_ATTEMPTS) {
                return $response;
            }

            usleep(self::RETRY_SLEEP_MICROSECONDS);
        }
    }
}